yarnPath: .yarn/releases/yarn-4.5.0.cjs
packageExtensions:
  '@sopt-makers/ui@2.0.2':
    peerDependencies:
      react-dom: '^18.2.0'
  '@storybook/addon-controls@8.0.4':
    peerDependencies:
      react: '^18.2.0'
      react-dom: '^18.2.0'
  '@storybook/addon-essentials@8.0.4':
    peerDependencies:
      react: '^18.2.0'
      react-dom: '^18.2.0'
  '@storybook/core-server@8.0.4':
    peerDependencies:
      react: '^18.2.0'
      react-dom: '^18.2.0'
  '@storybook/cli@8.0.4':
    peerDependencies:
      react: '^18.2.0'
      react-dom: '^18.2.0'
  '@storybook/manager-api@8.0.4':
    peerDependencies:
      react: '^18.2.0'
      react-dom: '^18.2.0'
  '@types/react-datepicker@6.2.0':
    peerDependencies:
      react: '^18.2.0'
      react-dom: '^18.2.0'
  '@typescript-eslint/utils@5.62.0':
    peerDependencies:
      typescript: '^5.4.4'
  'eslint-plugin-storybook@0.8.0':
    peerDependencies:
      react: '^18.2.0'
      react-dom: '^18.2.0'
      typescript: '^5.4.4'
  'storybook@8.0.4':
    peerDependencies:
      react: '^18.2.0'
      react-dom: '^18.2.0'
